name: Auto Tag & Version Bump

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump type (patch|minor|major)"
        required: true
        default: patch

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Current Version
        id: cur
        run: |
          VER_LINE=$(grep '^Version:' authentic-checker.php)
          CUR=${VER_LINE#Version: }
          echo "current=$CUR" >> $GITHUB_OUTPUT

      - name: Compute Next Version
        id: next
        run: |
          CUR=${{ steps.cur.outputs.current }}
          IFS='.' read -r MA MI PA <<< "$CUR"
          case "${{ github.event.inputs.bump }}" in
            major) MA=$((MA+1)); MI=0; PA=0 ;;
            minor) MI=$((MI+1)); PA=0 ;;
            patch) PA=$((PA+1)) ;;
            *) echo "Invalid bump"; exit 1 ;;
          esac
          NEXT="$MA.$MI.$PA"
          echo "next=$NEXT" >> $GITHUB_OUTPUT

      - name: Validate Changelog Entry
        run: |
          NEXT=${{ steps.next.outputs.next }}
          if ! grep -q "\[${NEXT}\]" CHANGELOG.md; then
            echo "No changelog entry for [${NEXT}] found. Please add it before bumping." >&2
            exit 1
          fi

      - name: Update Version Strings
        run: |
          NEXT=${{ steps.next.outputs.next }}
          sed -i "s/^Version: .*/Version: ${NEXT}/" authentic-checker.php
          sed -i "s/const WC_APC_VERSION = '.*';/const WC_APC_VERSION = '${NEXT}';/" authentic-checker.php
          # Changelog already validated; do not auto-insert placeholder.

      - name: Commit & Tag
        run: |
          NEXT=${{ steps.next.outputs.next }}
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add authentic-checker.php CHANGELOG.md
          git commit -m "chore: bump version to ${NEXT}"
          git tag -a v${NEXT} -m "Release ${NEXT}"
          git push origin HEAD --tags

      - name: Output Version
        run: echo "Bumped to ${{ steps.next.outputs.next }}"
